services:
  - type: web
    name: rag-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 --timeout 120 main:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
