services:
  - type: web
    name: rag-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT main:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000  # Ensure this value is set
